name: "CodeQL"

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Check
        run: echo "The cron job triggered successfully!"
