name: Gold Rate Pipeline

on:
  workflow_dispatch:

  schedule:
    # 9:00 AM IST, Monday-Saturday
    - cron: "0 9 * * 1-6"
      timezone: "Asia/Kolkata"

jobs:
  gold-rate-pipeline:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gold Rate Pipeline
        env:
          # LLM
          LLM_PROVIDER: groq
          LLM_MODEL: openai/gpt-oss-20b

          #GROQ
          GROQ_BASE_URL: https://api.groq.com/openai/v1
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

          #OpenRouter
          OPENROUTER_BASE_URL: https://openrouter.ai/api/v1
          OPENROUTER_API_KEY : ${{ secrets.OPENROUTER_API_KEY }}

          # Cloudinary
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

          # Instagram
          INSTAGRAM_APP_ID: ${{ secrets.INSTAGRAM_APP_ID}}
          INSTAGRAM_APP_SECRET: ${{ secrets.INSTAGRAM_APP_SECRET}}
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN}}
          INSTAGRAM_ACCOUNT_ID: ${{ secrets.INSTAGRAM_ACCOUNT_ID}}
          PUBLISHER_TYPE: instagram

        run: |
          python -m src.main